# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dTXaAnSD2ZUOBXAwrNa573gYV-Ilqro
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data"
colunas = ['compra', 'manutencao', 'portas', 'pessoas', 'porta_malas', 'seguranca', 'classe']
df = pd.read_csv(url, names=colunas)

print("Amostra dos dados originais:")
print(df.head(), "\n")

X_categorico = df.drop('classe', axis=1)
y_categorico = df['classe']

X = pd.get_dummies(X_categorico).values.astype('float32')


encoder = LabelEncoder()
y_numerico = encoder.fit_transform(y_categorico)
y = to_categorical(y_numerico)

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()


model.add(Dense(16, input_dim=X_treino.shape[1], activation='relu', name='Camada_Oculta_1'))

model.add(Dense(8, activation='relu', name='Camada_Oculta_2'))

model.add(Dense(4, activation='softmax', name='Camada_Saida'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print("Resumo da Arquitetura (Número de Parâmetros / Pesos):")
model.summary()
print("\nIniciando o treinamento...\n")

historico = model.fit(X_treino, y_treino,
                      epochs=50,
                      batch_size=32,
                      validation_split=0.2,
                      verbose=1)

perda, acuracia = model.evaluate(X_teste, y_teste, verbose=0)
print(f"\nAcurácia final nos dados de teste: {acuracia * 100:.2f}%\n")


plt.figure(figsize=(10, 5))
plt.plot(historico.history['loss'], label='Erro no Treino')
plt.plot(historico.history['val_loss'], label='Erro na Validação')
plt.title('Minimização da Função de Custo (Erro) ao longo das Épocas')
plt.ylabel('Erro (Entropia Cruzada)')
plt.xlabel('Época')
plt.legend()
plt.grid(True)
plt.show()