# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dTXaAnSD2ZUOBXAwrNa573gYV-Ilqro
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

url = "https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/master/Datasets/Mall_Customers.csv"

df = pd.read_csv(url)

print("Visão geral dos dados carregados:")
print(df.head(), "\n")


X = df.iloc[:, [3, 4]].values

kmeans = KMeans(n_clusters=5, init='k-means++', max_iter=300, n_init=10, random_state=42)

pred_y = kmeans.fit_predict(X)
centroides = kmeans.cluster_centers_

plt.figure(figsize=(10, 6))

plt.scatter(X[:, 0], X[:, 1], c=pred_y, s=50, cmap='plasma', alpha=0.7, label='Clientes')

plt.scatter(centroides[:, 0], centroides[:, 1], s=250, c='red', marker='X', edgecolor='black', label='Centroides')

plt.title('Agrupamento de Clientes do Kaggle (K-Means)', fontsize=14)
plt.xlabel('Renda Anual (k$)')
plt.ylabel('Pontuação de Gastos (1-100)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)

plt.show()

